'use client';
import {useEffect,useMemo,useState} from "react";
import {generateSigmaTest} from "@/lib/sigma";

type Msg={from:"bot"|"user";text:string};
type Step="welcome"|"name"|"surname"|"email"|"whatsapp"|"confirm"|"test"|"install"|"offer";
const progress:Record<Step,number>={welcome:1,name:1,surname:2,email:3,whatsapp:4,confirm:5,test:5,install:5,offer:5};
const initial={name:"",surname:"",email:"",whatsapp:"",utm_source:"",utm_medium:"",utm_content:""};
export default function Home(){const [step,setStep]=useState<Step>("welcome");const [msgs,setMsgs]=useState<Msg[]>([{from:"bot",text:"Oi! 👋 Eu sou o assistente da UnyFlick."},{from:"bot",text:"Quer assistir filmes, séries e canais ao vivo agora, de graça por 2h?"}]);const [input,setInput]=useState("");const [typing,setTyping]=useState(false);const [data,setData]=useState(initial);const [leadId,setLeadId]=useState("");const [error,setError]=useState("");const [test,setTest]=useState<{username:string;password:string;expiresAt:string;mock:boolean}|null>(null);
 useEffect(()=>{const p=new URLSearchParams(location.search);setData(d=>({...d,utm_source:p.get("utm_source")||"",utm_medium:p.get("utm_medium")||"",utm_content:p.get("utm_content")||""}))},[]);
 useEffect(()=>{const saved=localStorage.getItem("unyflick_lead_id");if(saved)setLeadId(saved)},[]);
 const save=async(p:any)=>{const id=leadId||crypto.randomUUID();if(!leadId){setLeadId(id);localStorage.setItem("unyflick_lead_id",id)}await fetch("/api/leads",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({...data,...p,id})}).catch(()=>{})};
 const bot=(text:string,next?:()=>void)=>{setTyping(true);setTimeout(()=>{setMsgs(m=>[...m,{from:"bot",text}]);setTyping(false);next?.()},900)};
 const answer=(text:string,nextStep:Step,reply=text)=>{setMsgs(m=>[...m,{from:"user",text:reply}]);setInput("");setError("");setStep(nextStep)};
 const askName=()=>{answer("Quero testar","name");bot("Perfeito. Qual é o seu nome?")};
 const askHow=()=>{answer("Como funciona?","welcome");bot("É simples: você recebe um acesso de teste por 2 horas para assistir ao catálogo no celular ou na TV. Sem compromisso. 😉",()=>bot("Se quiser experimentar, bora?"))};
 const validate=(s:string)=>{if(step==="name"||step==="surname")return s.trim().length>=2;if(step==="email")return /^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(s.trim());if(step==="whatsapp")return /^\d{10,11}$/.test(s.replace(/\D/g,""));return true};
 const submit=async()=>{const v=input.trim();if(!validate(v)){setError(step==="email"?"Digite um e-mail válido.":step==="whatsapp"?"Digite seu WhatsApp com DDD.":"Digite pelo menos 2 caracteres.");return}
 if(step==="name"){answer(v,"surname");setData(d=>({...d,name:v}));await save({name:v,stage:"surname"});bot(`Prazer, ${v}! E seu sobrenome?`)}
 else if(step==="surname"){answer(v,"email");setData(d=>({...d,surname:v}));await save({surname:v,stage:"email"});bot("Agora, qual é o seu melhor e-mail?")}
 else if(step==="email"){answer(v,"whatsapp");setData(d=>({...d,email:v}));await save({email:v,stage:"whatsapp"});bot("E qual é seu WhatsApp com DDD?")}
 else if(step==="whatsapp"){const w=v.replace(/\D/g,"");const r=await fetch("/api/leads",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({action:"check-whatsapp",whatsapp:w})}).then(x=>x.json()).catch(()=>({allowed:true}));if(!r.allowed){setError("Esse WhatsApp já utilizou um teste. Vamos direto para os planos?");return}answer(w,"confirm",w);setData(d=>({...d,whatsapp:w}));await save({whatsapp:w,stage:"confirm"});bot("Confira seus dados antes de gerar o acesso:",()=>bot(`${data.name||data.name} ${data.surname}\n📧 ${data.email}\n📱 ${w}\n\nEstá tudo certo?`))}
 };
 const generate=async()=>{setMsgs(m=>[...m,{from:"user",text:"Está certo, gerar meu teste"}]);setStep("test");setTyping(true);try{const t=await fetch("/api/sigma",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({name:data.name,surname:data.surname,whatsapp:data.whatsapp})}).then(r=>r.json());setTest(t);setTyping(false);await save({stage:"install",testGenerated:true,testUsername:t.username,testPassword:t.password});bot(`Seu teste de 2 horas está pronto!\n\n👤 Usuário: ${t.username}\n🔑 Senha: ${t.password}`)}catch{setTyping(false);setError("Não foi possível gerar agora. Tente novamente.");setStep("confirm")}};
 const click=(label:string)=>{if(label==="Quero testar")askName();else if(label==="Como funciona?")askHow();else if(label==="Bora"){answer("Bora","name");bot("Então vamos! Qual é o seu nome?")}else if(label==="Está certo, gerar meu teste")generate();else if(label==="Corrigir"){setStep("name");bot("Sem problema. Vamos corrigir. Qual é o seu nome?")}else if(label==="Instalar no celular"){setMsgs(m=>[...m,{from:"user",text:label}]);bot("No celular, eu te mostro o passo a passo de instalação na próxima tela.");}else if(label==="Instalar na TV"){setMsgs(m=>[...m,{from:"user",text:label}]);bot("Na TV, eu te mostro o passo a passo de instalação na próxima tela.");}else if(label==="Ver planos"){setMsgs(m=>[...m,{from:"user",text:label}]);bot("Perfeito! Aqui você pode escolher o plano que mais combina com você.");setStep("offer")}};
 useEffect(()=>{if(step==="offer")save({stage:"offer"})},[step]);
 const quick=useMemo(()=>step==="welcome"?["Quero testar","Como funciona?"]:step==="confirm"?["Está certo, gerar meu teste","Corrigir"]:step==="install"?["Instalar no celular","Instalar na TV"]:step==="offer"?["Ver planos"]:[],[step]);
 return <main className="app"><div className="chat"><header className="topbar"><div className="brand">Uny<span>Flick</span></div><div className="secure">● acesso seguro</div></header><div className="progress"><div className="progressTop"><span>Seu teste grátis</span><span>passo {progress[step]} de 5</span></div><div className="track"><div className="fill" style={{width:`${progress[step]/5*100}%`}}/></div></div><section className="messages">{msgs.map((m,i)=><div className={`row ${m.from}`} key={i}><div className="bubble">{m.text}</div></div>)}{typing&&<div className="row bot"><div className="typing"><i className="dot"/><i className="dot"/><i className="dot"/></div></div>}{test&&step==="test"&&<div className="row bot"><div className="bubble">Escolha onde vai instalar:</div></div>}{quick.length>0&&!typing&&<div className="quick">{quick.map(q=><button key={q} onClick={()=>click(q)}>{q}</button>)}</div>}{step==="install"&&!typing&&<div className="quick"><button onClick={()=>click("Instalar no celular")}>Instalar no celular</button><button onClick={()=>click("Instalar na TV")}>Instalar na TV</button></div>}{step==="offer"&&!typing&&<div className="quick"><button onClick={()=>click("Ver planos")}>Ver planos</button></div>}</section>{!["welcome","confirm","install","offer","test"].includes(step)&&<div className="composer"><div className="composerInner"><input value={input} onChange={e=>setInput(e.target.value)} onKeyDown={e=>{if(e.key==="Enter")submit()}} placeholder={step==="name"?"Seu nome...":step==="surname"?"Seu sobrenome...":step==="email"?"seu@email.com":"(00) 00000-0000"} autoFocus/><button disabled={!input.trim()||typing} onClick={submit}>Enviar</button></div>{error&&<div className="error">{error}</div>}</div>}</div></main>}
